routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/{path?}', 'welcome')->where('path', '^((?!admin).)*$');
Auth::routes();

Route::prefix('admin')->group(function () {

    Route::get('/', function (Request $request) {
        return view('admin.index');
    })->name('admin.index')->middleware('auth');

    Route::get('/login', function (Request $request) {
        return view('admin.pages.auth.login');
    })->name('admin.login');
    Route::post('/login','AuthController@login');

    Route::resource('categories', 'Admin\CategoriesController')->middleware('auth');
    Route::resource('partner', 'Admin\PartnerController');
    Route::post('file/upload', 'FileController@upload')->name('file.upload');
    Route::resource('user', 'Admin\UserController');
    Route::resource('devises', 'Admin\DeviseController')->middleware('auth');
    Route::resource('etapes', 'Admin\EtapeController')->middleware('auth');
});
Route::get('pays', 'PaysController@CountriesList');
/*Route::post('/register','Auth\RegisterController@create');
Route::post('/register','AuthController@register');
Route::post('/login','AuthController@login');
Route::get('email/verify/{id}', 'VerificationEmailController@verify')->name('verification.verify');
Route::get('email/resend', 'VerificationEmailController@resend')->name('verification.resend');
Route::post('/create_diapo','DiaporamaController@create_diapo');*/

resources/views/admin/devises/create.blade.php
@extends('admin.layouts.app')
@section('title', 'Devise')
@section('content')

<div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Creation Devise</h1>
          </div>
          <div class="section-body">
            <div class="row">
              <div class="mx-auto">
                <div class="card-body">
                  @include('admin.devises.form')
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

@endsection

resources/views/admin/devises/edit.blade.php
@extends('admin.layouts.app')
@section('title', 'Categories')

@section('content')
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Edit Devise</h1>
          </div>
          <div class="section-body">
            <div class="row">
              <div class=" mx-auto">
                <div class="card">
                  <div class="card-header">
                    <h4>Default Tab</h4>
                  </div>
                  <div class="card-body">
                     @include('admin.devises.form')
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
@endsection

resources/views/admin/devises/form.blade.php
<?php
if ($devise->id) {
    $options = ['method' => 'put', 'class'=>'needs-validation',  'url' => action('Admin\DeviseController@update', $devise), 'files' => false];
} else {
    $options = ['method' => 'post', 'class'=>'needs-validation', 'url' => action('Admin\DeviseController@store'), 'files' => false];
}
?>


@include('utilities.errors')
@include('utilities.flash')

{!! Form::model($devise, $options,['class'=>'','enctype'=>"multipart/form-data",'accept-charset'=>"utf-8"]) !!}
@csrf
<div class="card">
    <div class="card-header">
        <h4>Ajouter une devise</h4>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <div class="form-group">
            {!! Form::label('name', 'Nom') !!}
            {!! Form::text('name', null , ['class' => 'form-control', 'required'=>'required', 'placeholder'=>"Name or title of the devise..."]) !!}
        </div>
          
        <div class="card">
            <div class="card-footer text-right">
                <button class="btn btn-secondary" type="reset">Reset</button>
                <button class="btn btn-primary" type="submit">Validé</button>
            </div>
        </div>
    </div>
</div>
{!! Form::close() !!} 

resources/views/admin/devises/index.blade.php
@extends('admin.layouts.app')
@section('title', 'Devise')
@section('content')
<div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Listing Devise</h1>
          </div>
          <div class="section-body">
            <div class="row">
              <div class="col-12">
                <div class="card">
                  <div class="card-header">
                    <h4>Basic DataTables</h4>
                  </div>
                  <div class="card-body">
                    <div class="table-responsive">
                      <table class="table table-striped" id="table-1">
                        <thead>
                          <tr>
                            <th class="text-center">
                              #
                            </th>
                            <th>Name</th>
                            <th>Action</th>
                          </tr>
                        </thead>
                        <tbody>
                          @forelse($devises as $devise)
                            <tr>
                              <td>{{ $loop->iteration }}</td>
                              <td>{{ $devise->name }}</td>
                              
                              <td>
                                <a class="btn btn-primary btn-action mr-1" href="{{ route('devises.edit', $devise) }}" data-toggle="tooltip"  data-original-title="Edit">
                                  <i class="fas fa-pencil-alt"></i>
                                </a>
                                <a class="btn btn-primary btn-action mr-1" href="{{ route('devises.show', $devise) }}" data-toggle="tooltip"  data-original-title="Show">
                                  <i class="fas fa-pencil-alt"></i>
                                </a>
                                {!! Form::open([
                                    'method'=>'DELETE',
                                    'url' => route('devises.destroy', $devise ),
                                    'style' => 'display:inline'
                                ]) !!}
                                {!! Form::button('<i class="fas fa-trash"></i> ', array(
                                    'type' => 'submit',
                                    'class' => 'btn btn-danger',
                                    'title' => 'devise',
                                    'onclick' => 'return confirm(\'Vraiment supprimer cette devise ?\')'
                                )) !!}
                                {!! Form::close() !!}
                              </td>
                            </tr>
                          @empty
                          @endforelse
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
@endsection