routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/{path?}', 'welcome')->where('path', '^((?!admin).)*$');
Auth::routes();

Route::prefix('admin')->group(function () {

    Route::get('/', function (Request $request) {
        return view('admin.index');
    })->name('admin.index')->middleware('auth');

    Route::get('/login', function (Request $request) {
        return view('admin.pages.auth.login');
    })->name('admin.login');
    Route::post('/login','AuthController@login');

    Route::resource('categories', 'Admin\CategoriesController')->middleware('auth');
    Route::resource('partner', 'Admin\PartnerController');
    Route::post('file/upload', 'FileController@upload')->name('file.upload');
    Route::resource('user', 'Admin\UserController');
    Route::resource('devises', 'Admin\DeviseController')->middleware('auth');
    Route::resource('etapes', 'Admin\EtapeController')->middleware('auth');
});
Route::get('pays', 'PaysController@CountriesList');
/*Route::post('/register','Auth\RegisterController@create');
Route::post('/register','AuthController@register');
Route::post('/login','AuthController@login');
Route::get('email/verify/{id}', 'VerificationEmailController@verify')->name('verification.verify');
Route::get('email/resend', 'VerificationEmailController@resend')->name('verification.resend');
Route::post('/create_diapo','DiaporamaController@create_diapo');*/

app/Partenaires.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Illuminate\Database\Eloquent\SoftDeletes;

class Partenaires extends Model implements HasMedia
{
    use InteractsWithMedia;
    
    public $timestamps = false;
    protected $fillable = [
        'name',
    ];
    protected $appends = ['image'];

    public function getImageAttribute()
    {
        if($this->getMedia('image')->first()) {
            $arrayLinks = explode("public", $this->getMedia('image')->first()->getPath());
            $link = Storage::url($arrayLinks[count($arrayLinks) - 1]);
        } else {
            $link = asset('images/defaults/category.png');
        }
        return $link;
    }
}

resources/views/admin/partenaires/create.blade.php
@extends('admin.layouts.app')
@section('title', 'Partenaire')
@section('content')

<div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Creation Partenaire</h1>
          </div>
          <div class="section-body">
            <div class="row">
              <div class="mx-auto">
                <div class="card-body">
                  @include('admin.partenaires.form')
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

@endsection

resources/views/admin/partenaires/edit.blade.php
@extends('admin.layouts.app')
@section('title', 'Categories')

@section('content')
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Edit Category</h1>
          </div>
          <div class="section-body">
            <div class="row">
              <div class=" mx-auto">
                <div class="card">
                  <div class="card-header">
                    <h4>Default Tab</h4>
                  </div>
                  <div class="card-body">
                    <div  id="myTabContent">
                      <div class="fade show active" id="generale" role="tabpanel" aria-labelledby="generale-tab">  
                        @include('admin.categories.form')
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
@endsection

resources/views/admin/partenaires/form.blade.php
<?php
if ($partner->id) {
    $options = ['method' => 'put', 'class'=>'needs-validation',  'url' => action('Admin\PartnerController@update', $partner), 'files' => true];
} else {
    $options = ['method' => 'post', 'class'=>'needs-validation', 'url' => action('Admin\PartnerController@store'), 'files' => true];
}
?>


@include('utilities.errors')
@include('utilities.flash')
@section('styles')
    {{-- Dropzone js cdn --}}
    <link rel="stylesheet" type="text/css" href="{{asset('plugins/dropzone/dist/min/dropzone.min.css')}}">
    <link rel="stylesheet" href="{{ asset('css/croppie.css') }}" />
@endsection
{!! Form::model($partner, $options,['class'=>'','enctype'=>"multipart/form-data",'accept-charset'=>"utf-8"]) !!}
@csrf
<div class="card">
    <div class="card-header">
        <h4>Ajouter un partenaire</h4>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="form-group">
            <label for="document">Image (Importer une seule image)</label>
            <div class="dropzone" id="document-dropzone">
                <div class="fallback">
                    <input name="file" type="file" multiple/>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="form-group">
            {!! Form::label('name', 'Nom') !!}
            {!! Form::text('name', null , ['class' => 'form-control', 'required'=>'required', 'placeholder'=>"Name or title of the category..."]) !!}
        </div>
        <div class="card">
            <div class="card-footer text-right">
                <button class="btn btn-secondary" type="reset">Reset</button>
                <button class="btn btn-primary" type="submit">Validé</button>
            </div>
        </div>
    </div>
</div>
{!! Form::close() !!} 
@section('scripts')
    <script src="{{ asset('plugins/dropzone/dist/dropzone.js') }}"></script>
    <script src="{{ asset('js/croppie.js') }}"></script>
    @include('utilities.dropzone', ['model' => $partner]);
@endsection

resources/views/admin/partenaires/index.blade.php
@extends('admin.layouts.app')
@section('title', 'Partenaires')
@section('content')
<div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Listing Partenaires</h1>
          </div>
          <div class="section-body">
            <div class="row">
              <div class="col-12">
                <div class="card">
                  <div class="card-header">
                    <h4>Basic DataTables</h4>
                  </div>
                  <div class="card-body">
                    <div class="table-responsive">
                      <table class="table table-striped" id="table-1">
                        <thead>
                          <tr>
                            <th class="text-center">
                              #
                            </th>
                            <th>Name</th>
                            <th>Action</th>
                          </tr>
                        </thead>
                        <tbody>
                          @forelse($partners as $partner)
                            <tr>
                              <td>{{ $loop->iteration }}</td>
                              <td>{{ $partner->name }}</td>
                              
                              <td>
                                <a class="btn btn-primary btn-action mr-1" href="{{ route('partner.edit', $partner) }}" data-toggle="tooltip"  data-original-title="Edit">
                                  <i class="fas fa-pencil-alt"></i>
                                </a>
                                <a class="btn btn-primary btn-action mr-1" href="{{ route('partner.show', $partner) }}" data-toggle="tooltip"  data-original-title="Show">
                                  <i class="fas fa-pencil-alt"></i>
                                </a>
                                
                                {!! Form::open([
                                    'method'=>'DELETE',
                                    'url' => route('partner.destroy', $partner ),
                                    'style' => 'display:inline'
                                ]) !!}
                                {!! Form::button('<i class="fas fa-trash"></i> ', array(
                                    'type' => 'submit',
                                    'class' => 'btn btn-danger',
                                    'title' => 'partenaire',
                                    'onclick' => 'return confirm(\'Vraiment supprimer ce partenaire ?\')'
                                )) !!}  
                                {!! Form::close() !!}
                              </td>
                            </tr>
                          @empty
                          @endforelse
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
@endsection