routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/{path?}', 'welcome')->where('path', '^((?!admin).)*$');
Auth::routes();

Route::prefix('admin')->group(function () {

    Route::get('/', function (Request $request) {
        return view('admin.index');
    })->name('admin.index')->middleware('auth');

    Route::get('/login', function (Request $request) {
        return view('admin.pages.auth.login');
    })->name('admin.login');
    Route::post('/login','AuthController@login');

    Route::resource('categories', 'Admin\CategoriesController')->middleware('auth');
    Route::resource('partner', 'Admin\PartnerController');
    Route::post('file/upload', 'FileController@upload')->name('file.upload');
    Route::resource('user', 'Admin\UserController');
    Route::resource('devises', 'Admin\DeviseController')->middleware('auth');
    Route::resource('etapes', 'Admin\EtapeController')->middleware('auth');
});
Route::get('pays', 'PaysController@CountriesList');
/*Route::post('/register','Auth\RegisterController@create');
Route::post('/register','AuthController@register');
Route::post('/login','AuthController@login');
Route::get('email/verify/{id}', 'VerificationEmailController@verify')->name('verification.verify');
Route::get('email/resend', 'VerificationEmailController@resend')->name('verification.resend');
Route::post('/create_diapo','DiaporamaController@create_diapo');*/

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Categories;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Categories::all();
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = new Categories();
        return view('admin.categories.create', compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validation = $request->validate(array(
            'name' => 'required|min:3|unique:categories',
            'description' => 'required|string|min:6',
        ));

        $categories = new Categories();
        $categories->name = $request->input('name');
        $categories->description = $request->input('description');
        $categories->save();

        foreach ($request->input('document', []) as $file) {
            $categories->addMedia(storage_path('tmp/uploads/' . $file))->toMediaCollection('image');
        }

        return redirect(route('categories.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function show(Categories $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function edit(Categories $category)
    {
        return view('admin.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Categories $category)
    {
        $category = Categories::findOrFail($category->id);
        
        if (count($category->getMedia('image')) > 0) {
            foreach ($category->getMedia('image') as $media) {
                if (!in_array($media->file_name, $request->input('document', []))) {
                    $media->delete();
                }
            }
        }
        
        $media = $category->getMedia('image')->pluck('file_name')->toArray();

        foreach ($request->input('document', []) as $file) {
            if (count($media) === 0 || !in_array($file, $media)) {
                $category->addMedia(storage_path('tmp/uploads/' . $file))->toMediaCollection('image');
            }
        }

        $category->name = $request->input('name');
        $category->description = $request->input('description');
        $category->save();

        return redirect(route('categories.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function destroy(Categories $category)
    {
        $category = Categories::find($category->id);
        $category->delete();
        return  redirect()->route('categories.index');
        
    }

    public function categories()
    {
        $categories = Categories::all();
        return response()->json($categories);
    }

}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.app')
@section('title', 'Categorie')
@section('content')

<div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Creation Categorie</h1>
          </div>
          <div class="section-body">
            <div class="row">
              <div class="mx-auto">
                <div class="card-body">
                  @include('admin.categories.form')
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>

@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.app')
@section('title', 'Categories')

@section('content')
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Edit Category</h1>
          </div>
          <div class="section-body">
            <div class="row">
              <div class=" mx-auto">
                <div class="card">
                  <div class="card-header">
                    <h4>Default Tab</h4>
                  </div>
                  <div class="card-body">
                    <div  id="myTabContent">
                      <div class="fade show active" id="generale" role="tabpanel" aria-labelledby="generale-tab">  
                        @include('admin.categories.form')
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
@endsection

resources/views/admin/categories/form.blade.php
<?php
if ($category->id) {
    $options = ['method' => 'put', 'class'=>'needs-validation',  'url' => action('Admin\CategoriesController@update', $category), 'files' => true];
} else {
    $options = ['method' => 'post', 'class'=>'needs-validation', 'url' => action('Admin\CategoriesController@store'), 'files' => true];
}
?>


@include('utilities.errors')
@include('utilities.flash')
@section('styles')
    {{-- Dropzone js cdn --}}
    <link rel="stylesheet" type="text/css" href="{{asset('plugins/dropzone/dist/min/dropzone.min.css')}}">
    <link rel="stylesheet" href="{{ asset('css/croppie.css') }}" />
@endsection
{!! Form::model($category, $options,['class'=>'','enctype'=>"multipart/form-data",'accept-charset'=>"utf-8"]) !!}
@csrf
<div class="card">
    <div class="card-header">
        <h4>Ajouter une catégorie</h4>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="form-group">
            <label for="document">Image (Importer une seule image)</label>
            <div class="dropzone" id="document-dropzone">
                <div class="fallback">
                    <input name="file" type="file" multiple/>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="form-group">
            {!! Form::label('name', 'Nom') !!}
            {!! Form::text('name', null , ['class' => 'form-control', 'required'=>'required', 'placeholder'=>"Name or title of the category..."]) !!}
        </div>
        <div class="form-group">
            {!! Form::label('description','Description') !!}
            {!! Form::textarea('description', null , ['class' => 'form-control', 'required'=>'required']) !!}
        </div>
          
        <div class="card">
            <div class="card-footer text-right">
                <button class="btn btn-secondary" type="reset">Reset</button>
                <button class="btn btn-primary" type="submit">Validé</button>
            </div>
        </div>
    </div>
</div>
{!! Form::close() !!} 
@section('scripts')
    <script src="{{ asset('plugins/dropzone/dist/dropzone.js') }}"></script>
    <script src="{{ asset('js/croppie.js') }}"></script>
    @include('utilities.dropzone', ['model' => $category]);
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app')
@section('title', 'Categories')
@section('content')
<div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Listing Categories</h1>
          </div>
          <div class="section-body">
            <div class="row">
              <div class="col-12">
                <div class="card">
                  <div class="card-header">
                    <h4>Basic DataTables</h4>
                  </div>
                  <div class="card-body">
                    <div class="table-responsive">
                      <table class="table table-striped" id="table-1">
                        <thead>
                          <tr>
                            <th class="text-center">
                              #
                            </th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Action</th>
                          </tr>
                        </thead>
                        <tbody>
                          @forelse($categories as $category)
                            <tr>
                              <td>{{ $loop->iteration }}</td>
                              <td>{{ $category->name }}</td>
                              <td class="text-break">{{ $category->description }}</td>
                              
                              <td>
                                <a class="btn btn-primary btn-action mr-1" href="{{ route('categories.edit', $category) }}" data-toggle="tooltip"  data-original-title="Edit">
                                  <i class="fas fa-pencil-alt"></i>
                                </a>
                                <a class="btn btn-primary btn-action mr-1" href="{{ route('categories.show', $category) }}" data-toggle="tooltip"  data-original-title="Show">
                                  <i class="fas fa-pencil-alt"></i>
                                </a>
                                {{--<a class="btn btn-danger btn-action trigger--fire-modal-1" 
                                  data-toggle="tooltip" title="" 
                                  data-confirm="Are You Sure?|This action can not be undone. Do you want to continue?" 
                                  data-confirm-yes="alert('Deleted')" data-original-title="Delete">
                                  <i class="fas fa-trash"></i>
                                </a>--}}
                                {!! Form::open([
                                    'method'=>'DELETE',
                                    'url' => route('categories.destroy', $category ),
                                    'style' => 'display:inline'
                                ]) !!}
                                {!! Form::button('<i class="fas fa-trash"></i> ', array(
                                    'type' => 'submit',
                                    'class' => 'btn btn-danger',
                                    'title' => 'categorie',
                                    'onclick' => 'return confirm(\'Vraiment supprimer cette categorie ?\')'
                                )) !!}
                                {!! Form::close() !!}
                              </td>
                            </tr>
                          @empty
                          @endforelse
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
@endsection

resources/views/admin/categories/show.blade.php
@extends('admin.layouts.app')
@section('title', 'Client')

@section('content')
        <div class="main-content">
          <section class="section">
            <div class="section-header">
              <h1>Edit Admin</h1>
            </div>
            <div class="section-body">
              <div class="row">
                <div class="col-12 col-md-12 col-lg-10">
                  <div class="card profile-widget">
                    <div class="profile-widget-header">                     
                      <div class="profile-widget-items">
                        <div class="profile-widget-item">
                          <div class="profile-widget-item-label">Compte</div>
                          <div class="profile-widget-item-value">{{$client->numero_abonnement}} </div>
                        </div>
                        <div class="profile-widget-item">
                          <div class="profile-widget-item-label">Nom</div>
                          <div class="profile-widget-item-value">{{$client->name}} {{$client->last_name}}</div>
                        </div>
                        <div class="profile-widget-item">
                          <div class="profile-widget-item-label">Date compte</div>
                          <div class="profile-widget-item-value">{{$client->subscription_date}}</div>
                        </div>
                        <div class="profile-widget-item">
                          <div class="profile-widget-item-label">Telephone</div>
                          <div class="profile-widget-item-value">{{$client->telephone}}</div>
                        </div>
                        <div class="profile-widget-item">
                          <div class="profile-widget-item-label">Site</div>
                          <div class="profile-widget-item-value">{{ $client->site_id ? $client->site->name : '' }} </div>
                        </div>
                        <div class="profile-widget-item">
                          <div class="profile-widget-item-label">Solde</div>
                          <div class="profile-widget-item-value">{{$client->solde}}</div>
                        </div>
                      </div>
                    </div>
                    
                    <div class="card-footer text-center">
                      <div class="font-weight-bold mb-2">Follow Ujang On</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </div>
@endsection